export const BUTT = "butt",
	SQUARE = "square",
	ROUND = "round",
	MILTER = "milter",
	BEVEL = "bevel",
	MITER = "miter",
	LEFT = "left",
	RIGHT = "right",
	CENTER = "center",
	START = "start",
	END = "end",
	TOP = "top",
	HANGING = "hanging",
	MIDDLE = "middle",
	ALPHABETIC = "alphabetic",
	IDEOGRAPHIC = "ideographic",
	BOTTOM = "bottom",
	// font stretch properties
	ULTRA_CONDENSED = "ultra-condensed", // 50%
	EXTRA_CONDENSED = "extra-condensed", // 62.5%
	CONDENSED = "condensed", // 75%
	SEMI_CONDENSED = "semi-condensed", // 87.5%
	NORMAL = "normal", // 100%
	SEMI_EXPANDED = "semi-expanded", // 112.5%
	EXPANDED = "expanded", // 125%
	EXTRA_EXPANDED = "extra-expanded", // 150%
	ULTRA_EXPANDED = "ultra-expanded", // 200%
	// font size properties
	XX_SMALL = "xx-small",
	X_SMALL = "x-small",
	SMALL = "small",
	MEDIUM = "medium",
	LARGE = "large",
	X_LARGE = "x-large",
	XX_LARGE = "xx-large",
	XXX_LARGE = "xxx-large",
	LARGER = "larger",
	SMALLER = "smaller",
	// font style properties
	ITALIC = "italic",
	OBLIQUE = "oblique";
